name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Markdown
      uses: DavidAnson/markdownlint-cli2-action@v13
      with:
        globs: "*.md"
        config: |
          MD013:
            line_length: 100
            codeblocks: false
          MD033:
            allowed_elements:
            - br
